import {View, Text} from 'react-native';
import React from 'react';
import SkeletonPlaceholder from 'react-native-skeleton-placeholder';
import {moderateScale} from 'react-native-size-matters';
import {colorTheme} from '../../constants/ColorConstants';
const {defaultBorder} = colorTheme;
const CategoriesSkeleton = () => {
  return (
    <SkeletonPlaceholder borderRadius={4}>
      <SkeletonPlaceholder.Item flexDirection="row" gap={10}>
        <SkeletonPlaceholder.Item
          height={moderateScale(130)}
          paddingVertical={moderateScale(10)}
          paddingLeft={moderateScale(12)}
          paddingRight={moderateScale(5)}
          borderWidth={1}
          borderColor={defaultBorder}
          width={'48%'}>
          <SkeletonPlaceholder.Item
            height={moderateScale(29)}
            width={moderateScale(109)}
          />
          <SkeletonPlaceholder.Item
            height={moderateScale(10)}
            marginTop={6}
            width={moderateScale(95)}
          />
          <SkeletonPlaceholder.Item
            height={moderateScale(10)}
            marginTop={2}
            width={moderateScale(95)}
          />
          <SkeletonPlaceholder.Item
            height={moderateScale(50)}
            marginTop={5}
            alignSelf="flex-end"
            width={moderateScale(50)}
          />
        </SkeletonPlaceholder.Item>
        <SkeletonPlaceholder.Item
          height={moderateScale(130)}
          paddingVertical={moderateScale(10)}
          paddingLeft={moderateScale(12)}
          paddingRight={moderateScale(5)}
          borderWidth={1}
          borderColor={defaultBorder}
          width={'48%'}>
          <SkeletonPlaceholder.Item
            height={moderateScale(29)}
            width={moderateScale(109)}
          />
          <SkeletonPlaceholder.Item
            height={moderateScale(10)}
            marginTop={6}
            width={moderateScale(95)}
          />
          <SkeletonPlaceholder.Item
            height={moderateScale(10)}
            marginTop={2}
            width={moderateScale(95)}
          />
          <SkeletonPlaceholder.Item
            height={moderateScale(50)}
            marginTop={5}
            alignSelf="flex-end"
            width={moderateScale(50)}
          />
        </SkeletonPlaceholder.Item>
      </SkeletonPlaceholder.Item>

      <SkeletonPlaceholder.Item flexDirection="row" marginTop={15} gap={10}>
        <SkeletonPlaceholder.Item
          height={moderateScale(70)}
          paddingVertical={moderateScale(10)}
          paddingLeft={moderateScale(12)}
          paddingRight={moderateScale(5)}
          borderColor={defaultBorder}
          borderWidth={1}
          width={'48%'}>
          <SkeletonPlaceholder.Item
            gap={10}
            justifyContent="center"
            alignItems="center"
            flexDirection="row">
            <SkeletonPlaceholder.Item>
              <SkeletonPlaceholder.Item
                height={moderateScale(26)}
                width={moderateScale(77)}
              />
              <SkeletonPlaceholder.Item
                height={moderateScale(13)}
                marginTop={6}
                width={moderateScale(73)}
              />
            </SkeletonPlaceholder.Item>
            <SkeletonPlaceholder.Item
              height={moderateScale(50)}
              marginTop={5}
              // alignSelf=""
              width={moderateScale(50)}
            />
          </SkeletonPlaceholder.Item>
        </SkeletonPlaceholder.Item>
        <SkeletonPlaceholder.Item
          height={moderateScale(70)}
          paddingVertical={moderateScale(10)}
          paddingLeft={moderateScale(12)}
          paddingRight={moderateScale(5)}
          borderWidth={1}
          borderColor={defaultBorder}
          width={'48%'}>
          <SkeletonPlaceholder.Item
            gap={10}
            justifyContent="center"
            alignItems="center"
            flexDirection="row">
            <SkeletonPlaceholder.Item>
              <SkeletonPlaceholder.Item
                height={moderateScale(26)}
                width={moderateScale(77)}
              />
              <SkeletonPlaceholder.Item
                height={moderateScale(13)}
                marginTop={6}
                width={moderateScale(73)}
              />
            </SkeletonPlaceholder.Item>
            <SkeletonPlaceholder.Item
              height={moderateScale(50)}
              marginTop={5}
              // alignSelf=""
              width={moderateScale(50)}
            />
          </SkeletonPlaceholder.Item>
        </SkeletonPlaceholder.Item>
      </SkeletonPlaceholder.Item>
      <SkeletonPlaceholder.Item flexDirection="row" marginTop={15} gap={10}>
        <SkeletonPlaceholder.Item
          height={moderateScale(130)}
          paddingVertical={moderateScale(10)}
          paddingLeft={moderateScale(12)}
          paddingRight={moderateScale(5)}
          borderWidth={1}
          borderColor={defaultBorder}
          width={'48%'}>
          <SkeletonPlaceholder.Item
            height={moderateScale(29)}
            width={moderateScale(109)}
          />
          <SkeletonPlaceholder.Item
            height={moderateScale(10)}
            marginTop={6}
            width={moderateScale(95)}
          />
          <SkeletonPlaceholder.Item
            height={moderateScale(10)}
            marginTop={2}
            width={moderateScale(95)}
          />
          <SkeletonPlaceholder.Item
            height={moderateScale(50)}
            marginTop={5}
            alignSelf="flex-end"
            width={moderateScale(50)}
          />
        </SkeletonPlaceholder.Item>
        <SkeletonPlaceholder.Item
          height={moderateScale(130)}
          paddingVertical={moderateScale(10)}
          paddingLeft={moderateScale(12)}
          paddingRight={moderateScale(5)}
          borderWidth={1}
          borderColor={defaultBorder}
          width={'48%'}>
          <SkeletonPlaceholder.Item
            height={moderateScale(29)}
            width={moderateScale(109)}
          />
          <SkeletonPlaceholder.Item
            height={moderateScale(10)}
            marginTop={6}
            width={moderateScale(95)}
          />
          <SkeletonPlaceholder.Item
            height={moderateScale(10)}
            marginTop={2}
            width={moderateScale(95)}
          />
          <SkeletonPlaceholder.Item
            height={moderateScale(50)}
            marginTop={5}
            alignSelf="flex-end"
            width={moderateScale(50)}
          />
        </SkeletonPlaceholder.Item>
      </SkeletonPlaceholder.Item>
    </SkeletonPlaceholder>
  );
};

export default CategoriesSkeleton;
