require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '17.0'
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
if linkage != nil
  PodIOS::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
end

target 'CustomerMoveit' do
  use_frameworks! :linkage => :static
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
  )

  target 'CustomerMoveitTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
  end
end
